import Head from 'next/head';

import { PostCard, PostWidget, Categories } from '../components';

const post = [
  { title: 'test', excerpt: 'Learn react nextg' },
  {
    title: 'Anoter test',
    excerpt: 'Learn react tailwind and all sorts of weirdness',
  },
];

export default function Home() {
  return (
    <div className="container mx-auto px-10 mb-8">
      <Head>
        <title>Halidays Journal</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-12">
        <div className="lg:col-span-8 col-span-1">
          {post.map((p, index) => (
            <PostCard key={p.title} post={p} />
          ))}
        </div>
        <div className="lg:col-span-4 col-span-1">
          <div className="lg:sticky relative top-8">
            <PostWidget />
            <Categories />
          </div>
        </div>
      </div>
    </div>
  );
}
